baseURL: http://www.example.com
title: Adam Smith
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: bw
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
enableEmoji: yes
params:
  author: Adam Smith
  avatarURL: images/avatar.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customRemoteJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Adam Smith's personal website
  hideColorSchemeToggle: no
  info:
    - Business Analytics Major
    - Machine Learning Enthusiast 
  keywords: ML, AI, Data Science
  maxSeeAlsoItems: 5
  rtl: no
  since: 2019
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/johndoe/
      weight: 1
    - icon: fa fa-2x fa-twitter
      name: Twitter
      url: https://twitter.com/johndoe/
      weight: 2
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/johndoe/
      weight: 3
    
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact 
          url: contact/
          weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
